### ISSUE TITLE
Problematic country board data statistic

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-airflow-dags#138]
https://github.com/Greenstand/treetracker-airflow-dags/blob/main/lib/country_leader_board.py

This task is for statisticing the country leader board, but it is wrong in the North American continent: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/205565041-66f0923d-a178-4693-be33-00b5bef12964.png">

https://beta-map.treetracker.org/top?bounds=-126.56250000000001,-77.69287033641926,126.56250000000001,77.69287033641928

**Comment by asarephilip** [comment]
@dadiorchen 
I would like to work on this issue but I don't see the problem. 
Can you please add some details?

**Comment by wesleycheung0** [comment]
@asarephilip 
I am guessing the problem that @dadiorchen referring to is that there are multiple identical countries showing up in the leaderboard. For example under North America, United States shows up twice. Similar issues also happens to Australia as well.

**Comment by dadiorchen** [comment]
@wesleycheung0 @asarephilip yes, I guess it is a bit difficult to reproduce it in dev env, so please reach to me on slack so I can give you more details

**Comment by dadiorchen** [comment]
@wesleycheung0 is this the code above to solve our problem?

**Comment by wesleycheung0** [comment]
@dadiorchen I just made some [edit](https://github.com/Greenstand/treetracker-airflow-dags/commit/245c7d7b4106809c843dcb0015f17551b5a4f314) to the original commit . It should solve this issue, but i can't verify it as i do not have access to the prod.

**Comment by dadiorchen** [comment]
@wesleycheung0 awesome! can you raise a pr for this? here is a guide book for github: https://docs.greenstand.org/engineering/tools#github

**Comment by huang-pan** [comment]
I got this to work. I'll open up a PR for this issue.

**Comment by huang-pan** [comment]
The problem is that there is dirty data in the region table. There are multiple region ids for the same country name, e.g.:

`select distinct(id), name from region
where name = 'United States'
order by id`

returns

6632869	"United States"
6632870	"United States"
6632871	        "United States"
6632872	"United States"
6632873	"United States"
6632874	"United States"
6632875	"United States"

<img width="1440" alt="Screen Shot 2023-02-11 at 11 10 56 PM" src="https://user-images.githubusercontent.com/10567714/218342848-ce2f93e8-ae7d-49ad-84c2-52e788c4b417.png">

this SQL query works:

`with top_countries_cte as (
  -- this query will group by country name and sum all the planted trees for the country
  -- see below for why we have to do this: there are multiple region ids for a given name
  select sum(rr.planted) as planted, region.name from (
    -- count the number of trees for each region id in a specific continent
    select count(distinct(tree_id)) planted, region_id from active_tree_region
    where region_id in (
      --- select records that it's centroid is within the polygon
      select region.id from region 
      join (select id,name,geom from region where type_id in (select id from region_type where type = 'continents') and name = 'North America') continent
      on ST_Contains(continent.geom, region.centroid)
      where type_id in (select id from region_type where type = 'country')
    )
    group by region_id
    order by planted desc
  ) rr
  left join region on rr.region_id = region.id
  group by region.name
  order by planted desc
  limit 10
),
region_cte as (
  -- The problem is that there is dirty data in the region table. There are multiple region ids for the same country name, e.g.:
  -- select distinct(id), name from region where name = 'United States' order by id
  -- returns id 6632869, 6632870, 6632871, 6632872, 6632873, 6632874, 6632875, etc. for 'United States'
  -- to fix this, we choose the first id & centroid associated with the 'United States'
  -- https://stackoverflow.com/questions/6841605/get-top-1-row-of-each-group
	select distinct(name), id, centroid, ROW_NUMBER() OVER (PARTITION BY name ORDER BY id DESC) AS rn
	from region
	order by name, rn
), region_name_cte as (
  select * from region_cte
  WHERE rn = 1
)
-- add the centroid to the number of trees for each country
select planted, top_countries_cte.name, centroid from top_countries_cte
left join region_name_cte
on top_countries_cte.name = region_name_cte.name
order by planted desc`

<img width="1440" alt="Screen Shot 2023-02-12 at 3 15 24 PM" src="https://user-images.githubusercontent.com/10567714/218343134-4c52856e-f8fd-478d-ba36-b24ffe6aebc5.png">

**Comment by dadiorchen** [comment]
@huang-pan yea, you are right, but maybe it is not wrong data, it is because the are multiple area/part for some country, like some abroad territories outside the mainland, so maybe we need to recognize this, and sum them up.

**Comment by wesleycheung0** [comment]
Hey @huang-pan I opened a [pull request](https://github.com/Greenstand/treetracker-airflow-dags/pull/162) earlier to solve this problem. My approach was to sum it up all duplicate Region name down the stream. If you have access to prod, could you help me to review it. Thanks!

**Comment by huang-pan** [comment]
> Hey @huang-pan I opened a [pull request](https://github.com/Greenstand/treetracker-airflow-dags/pull/162) earlier to solve this problem. My approach was to sum it up all duplicate Region name down the stream. If you have access to prod, could you help me to review it. Thanks!

yeah I reviewed it, thanks for the help! The only thing missing was that it didn't solve the problem of multiple region id associated with the same name:

<img width="1440" alt="Screen Shot 2023-02-13 at 8 26 44 PM" src="https://user-images.githubusercontent.com/10567714/218639495-8e18ef9f-7074-4e72-8a5e-c78a9e306e16.png">

In my PR I arbitrarily chose the smallest region id and its associated centroid to display:

<img width="1440" alt="Screen Shot 2023-02-13 at 8 11 53 PM" src="https://user-images.githubusercontent.com/10567714/218639891-a4be8977-811a-4353-9d7d-1f24fc8b3bea.png">

**Comment by huang-pan** [comment]
PR https://github.com/Greenstand/treetracker-airflow-dags/pull/184 tested and working.

can speed up query by adding a b-tree index on type_id column in region table

**Comment by dadiorchen** [comment]
We can run it weekly

**Comment by dadiorchen** [comment]
@huang-pan  taking the biggest area as the country and center point is better? So what's your center point for US?

**Comment by huang-pan** [comment]
> We can run it weekly

You can probably add indexes to the region table to speed up queries, to all columns that are used in WHERE and ORDER BY clauses, like the name, id, and type_id columns.

**Comment by huang-pan** [comment]
> @huang-pan taking the biggest area as the country and center point is better? So what's your center point for US?

Good idea! I updated the SQL query:

<img width="1440" alt="Screen Shot 2023-02-14 at 7 59 05 PM" src="https://user-images.githubusercontent.com/10567714/218925847-144f6b0e-9fb9-44c4-83ec-e2ff9e824fa3.png">

**Comment by huang-pan** [comment]
PR https://github.com/Greenstand/treetracker-airflow-dags/pull/184 has been updated and tested working.

**Comment by dadiorchen** [comment]
@huang-pan thank you for the contribution, this is perfect!
